//load the mongoose lib.
const mongoose = require('mongoose');

//Designing of entire medicines collection of database i.e medicineDB.
const medicineSchema = new mongoose.Schema({
       'medicine_name': { type: 'String', required: true },
       'medicine_comp': { type: 'String', required: true },
       'used_for': { type: 'String' },
       "medicine_image": { type: 'String' },
       'medicine_price': { type: Number, required: true },
       'medicine_entry': { type: Date, required: true, default: new Date() }
}, { versionKey: false });       //name          //schema        //collections
module.exports = mongoose.model("medicineModel", medicineSchema, "medicines");

console.log("Medicine model is ready to use");//versionKey __v  field will not get generated by mongoose.